[tools]
github-cli = "2.83.2"
"go:github.com/go-delve/delve/cmd/dlv" = "1.26.0"
## Sync with templates/scripts/devbase.sh.tpl
gojq = "0.12.18"
mage = "1.14.0"
"github:getoutreach/ci" = "1.6.14"
# linters
buf = "1.60.0"
gofumpt = "0.9.2"
golangci-lint = "2.8.0"
shellcheck = "0.9.0"
shfmt = "3.7.0"
"github:getoutreach/lintroller" = "1.19.0"
"go:golang.org/x/tools/cmd/goimports" = "0.5.0"
