[task_config]
includes = [".bootstrap/.mise/tasks", ".mise/tasks"]

[env]
CIRCLECI_ORB_PATH = "orbs/shared"
CIRCLECI_ORB_NAME = "getoutreach/shared"

## <<Stencil::Block(customMiseEnvironment)>>

## <</Stencil::Block>>

[hooks]
enter = ["$MISE_PROJECT_ROOT/scripts/devbase.sh"]

## <<Stencil::Block(customMiseHooks)>>

## <</Stencil::Block>>

[tools]
"npm:prettier" = "2"
circleci = "latest"
## <<Stencil::Block(customMiseTools)>>
bats = "latest"
## <</Stencil::Block>>

## <<Stencil::Block(extraMise)>>
[tasks."stencil:post:mise"]
description = "Upgrades the devbase tool config + lockfile"
run = [
  "./shell/mise.sh upgrade --env devbase --before 7d",
  "./shell/mise.sh lock --env devbase",
]
## <</Stencil::Block>>
