[tools]
"aqua:fullstorydev/grpcui" = "1.3.1"
github-cli = "2.83.2"
"go:github.com/go-delve/delve/cmd/dlv" = "1.26.0"
"go:github.com/mattn/goveralls" = "0.0.11"
## Sync with templates/scripts/devbase.sh.tpl
gojq = "0.12.18"
gotestsum = "1.13.0"
mage = "1.14.0"
"github:getoutreach/ci" = "1.6.14"
# Delibird telemetry
"github:getoutreach/orc" = "latest"
# linters
buf = "1.60.0"
go-jsonnet = "0.19.1"
gofumpt = "0.9.2"
golangci-lint = "2.9.0"
kubeconform = "0.6.4"
shellcheck = "0.11.0"
shfmt = "3.7.0"
tombi = "0.7.27"
"github:getoutreach/lintroller" = "1.19.0"
"go:golang.org/x/tools/cmd/goimports" = "0.5.0"
