[tools]
github-cli = "2.83.2"
## Sync with templates/scripts/devbase.sh.tpl
gojq = "0.12.18"
mage = "1.14.0"
"github:getoutreach/ci" = "1.6.14"
# linters
buf = "1.60.0"
golangci-lint = "2.7.2"
shellcheck = "0.9.0"
shfmt = "3.7.0"
"github:getoutreach/lintroller" = "1.19.0"
